from Ncore.types.input_peer import InputPeerUser

class MessageEntity: ...
class InputReplyTo: ...
class ReplyMarkup: ...
class InputPeer: ...
class InputQuickReplyShortcut: ...
class SuggestedPost: ...