# Copyright 2026 zovdev
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

from __future__ import annotations
from typing import TYPE_CHECKING, Union, TypeAlias

if TYPE_CHECKING:
    from .account import *
    from .auth import *
    from .bots import *
    from .channels import *
    from .chatlists import *
    from .contacts import *
    from .fragment import *
    from .general import *
    from .help import *
    from .messages import *
    from .payments import *
    from .phone import *
    from .photos import *
    from .premium import *
    from .smsjobs import *
    from .stats import *
    from .stickers import *
    from .storage import *
    from .stories import *
    from .updates import *
    from .upload import *
    from .users import *

AnyAccountAuthorizationForm: TypeAlias = 'AccountAuthorizationForm'
AnyAccountAuthorizations: TypeAlias = 'AccountAuthorizations'
AnyAccountAutoDownloadSettings: TypeAlias = 'AccountAutoDownloadSettings'
AnyAccountAutoSaveSettings: TypeAlias = 'AccountAutoSaveSettings'
AnyAccountBusinessChatLinks: TypeAlias = 'AccountBusinessChatLinks'
AnyAccountChatThemes: TypeAlias = Union['AccountChatThemes', 'AccountChatThemesNotModified']
AnyAccountConnectedBots: TypeAlias = 'AccountConnectedBots'
AnyAccountContentSettings: TypeAlias = 'AccountContentSettings'
AnyAccountDaysTTL: TypeAlias = 'AccountDaysTTL'
AnyAccountEmailVerified: TypeAlias = Union['AccountEmailVerified', 'AccountEmailVerifiedLogin']
AnyAccountEmojiStatuses: TypeAlias = Union['AccountEmojiStatuses', 'AccountEmojiStatusesNotModified']
AnyAccountPaidMessagesRevenue: TypeAlias = 'AccountPaidMessagesRevenue'
AnyAccountPasskeyRegistrationOptions: TypeAlias = 'AccountPasskeyRegistrationOptions'
AnyAccountPasskeys: TypeAlias = 'AccountPasskeys'
AnyAccountPassword: TypeAlias = 'AccountPassword'
AnyAccountPasswordInputSettings: TypeAlias = 'AccountPasswordInputSettings'
AnyAccountPasswordSettings: TypeAlias = 'AccountPasswordSettings'
AnyAccountPrivacyRules: TypeAlias = 'AccountPrivacyRules'
AnyAccountResetPasswordResult: TypeAlias = Union['AccountResetPasswordFailedWait', 'AccountResetPasswordOk', 'AccountResetPasswordRequestedWait']
AnyAccountResolvedBusinessChatLinks: TypeAlias = 'AccountResolvedBusinessChatLinks'
AnyAccountSavedMusicIds: TypeAlias = Union['AccountSavedMusicIds', 'AccountSavedMusicIdsNotModified']
AnyAccountSavedRingtone: TypeAlias = Union['AccountSavedRingtone', 'AccountSavedRingtoneConverted']
AnyAccountSavedRingtones: TypeAlias = Union['AccountSavedRingtones', 'AccountSavedRingtonesNotModified']
AnyAccountSentEmailCode: TypeAlias = 'AccountSentEmailCode'
AnyAccountTakeout: TypeAlias = 'AccountTakeout'
AnyAccountThemes: TypeAlias = Union['AccountThemes', 'AccountThemesNotModified']
AnyAccountTmpPassword: TypeAlias = 'AccountTmpPassword'
AnyAccountWallPapers: TypeAlias = Union['AccountWallPapers', 'AccountWallPapersNotModified']
AnyAccountWebAuthorizations: TypeAlias = 'AccountWebAuthorizations'
AnyAttachMenuBot: TypeAlias = 'AttachMenuBot'
AnyAttachMenuBotIcon: TypeAlias = 'AttachMenuBotIcon'
AnyAttachMenuBotIconColor: TypeAlias = 'AttachMenuBotIconColor'
AnyAttachMenuBots: TypeAlias = Union['AttachMenuBots', 'AttachMenuBotsNotModified']
AnyAttachMenuBotsBot: TypeAlias = 'AttachMenuBotsBot'
AnyAttachMenuPeerType: TypeAlias = Union['AttachMenuPeerTypeBotPM', 'AttachMenuPeerTypeBroadcast', 'AttachMenuPeerTypeChat', 'AttachMenuPeerTypePM', 'AttachMenuPeerTypeSameBotPM']
AnyAuctionBidLevel: TypeAlias = 'AuctionBidLevel'
AnyAuthAuthorization: TypeAlias = Union['AuthAuthorization', 'AuthAuthorizationSignUpRequired']
AnyAuthCodeType: TypeAlias = Union['AuthCodeTypeCall', 'AuthCodeTypeFlashCall', 'AuthCodeTypeFragmentSms', 'AuthCodeTypeMissedCall', 'AuthCodeTypeSms']
AnyAuthExportedAuthorization: TypeAlias = 'AuthExportedAuthorization'
AnyAuthLoggedOut: TypeAlias = 'AuthLoggedOut'
AnyAuthLoginToken: TypeAlias = Union['AuthLoginToken', 'AuthLoginTokenMigrateTo', 'AuthLoginTokenSuccess']
AnyAuthPasskeyLoginOptions: TypeAlias = 'AuthPasskeyLoginOptions'
AnyAuthPasswordRecovery: TypeAlias = 'AuthPasswordRecovery'
AnyAuthSentCode: TypeAlias = Union['AuthSentCode', 'AuthSentCodePaymentRequired', 'AuthSentCodeSuccess']
AnyAuthSentCodeType: TypeAlias = Union['AuthSentCodeTypeApp', 'AuthSentCodeTypeCall', 'AuthSentCodeTypeEmailCode', 'AuthSentCodeTypeFirebaseSms', 'AuthSentCodeTypeFlashCall', 'AuthSentCodeTypeFragmentSms', 'AuthSentCodeTypeMissedCall', 'AuthSentCodeTypeSetUpEmailRequired', 'AuthSentCodeTypeSms', 'AuthSentCodeTypeSmsPhrase', 'AuthSentCodeTypeSmsWord']
AnyAuthorization: TypeAlias = 'Authorization'
AnyAutoDownloadSettings: TypeAlias = 'AutoDownloadSettings'
AnyAutoSaveException: TypeAlias = 'AutoSaveException'
AnyAutoSaveSettings: TypeAlias = 'AutoSaveSettings'
AnyAvailableEffect: TypeAlias = 'AvailableEffect'
AnyAvailableReaction: TypeAlias = 'AvailableReaction'
AnyBankCardOpenUrl: TypeAlias = 'BankCardOpenUrl'
AnyBaseTheme: TypeAlias = Union['BaseThemeArctic', 'BaseThemeClassic', 'BaseThemeDay', 'BaseThemeNight', 'BaseThemeTinted']
AnyBirthday: TypeAlias = 'Birthday'
AnyBoost: TypeAlias = 'Boost'
AnyBotApp: TypeAlias = Union['BotApp', 'BotAppNotModified']
AnyBotAppSettings: TypeAlias = 'BotAppSettings'
AnyBotBusinessConnection: TypeAlias = 'BotBusinessConnection'
AnyBotCommand: TypeAlias = 'BotCommand'
AnyBotCommandScope: TypeAlias = Union['BotCommandScopeChatAdmins', 'BotCommandScopeChats', 'BotCommandScopeDefault', 'BotCommandScopePeer', 'BotCommandScopePeerAdmins', 'BotCommandScopePeerUser', 'BotCommandScopeUsers']
AnyBotInfo: TypeAlias = 'BotInfo'
AnyBotInlineMessage: TypeAlias = Union['BotInlineMessageMediaAuto', 'BotInlineMessageMediaContact', 'BotInlineMessageMediaGeo', 'BotInlineMessageMediaInvoice', 'BotInlineMessageMediaVenue', 'BotInlineMessageMediaWebPage', 'BotInlineMessageText']
AnyBotInlineResult: TypeAlias = Union['BotInlineMediaResult', 'BotInlineResult']
AnyBotMenuButton: TypeAlias = Union['BotMenuButton', 'BotMenuButtonCommands', 'BotMenuButtonDefault']
AnyBotPreviewMedia: TypeAlias = 'BotPreviewMedia'
AnyBotVerification: TypeAlias = 'BotVerification'
AnyBotVerifierSettings: TypeAlias = 'BotVerifierSettings'
AnyBotsBotInfo: TypeAlias = 'BotsBotInfo'
AnyBotsPopularAppBots: TypeAlias = 'BotsPopularAppBots'
AnyBotsPreviewInfo: TypeAlias = 'BotsPreviewInfo'
AnyBusinessAwayMessage: TypeAlias = 'BusinessAwayMessage'
AnyBusinessAwayMessageSchedule: TypeAlias = Union['BusinessAwayMessageScheduleAlways', 'BusinessAwayMessageScheduleCustom', 'BusinessAwayMessageScheduleOutsideWorkHours']
AnyBusinessBotRecipients: TypeAlias = 'BusinessBotRecipients'
AnyBusinessBotRights: TypeAlias = 'BusinessBotRights'
AnyBusinessChatLink: TypeAlias = 'BusinessChatLink'
AnyBusinessGreetingMessage: TypeAlias = 'BusinessGreetingMessage'
AnyBusinessIntro: TypeAlias = 'BusinessIntro'
AnyBusinessLocation: TypeAlias = 'BusinessLocation'
AnyBusinessRecipients: TypeAlias = 'BusinessRecipients'
AnyBusinessWeeklyOpen: TypeAlias = 'BusinessWeeklyOpen'
AnyBusinessWorkHours: TypeAlias = 'BusinessWorkHours'
AnyCdnConfig: TypeAlias = 'CdnConfig'
AnyCdnPublicKey: TypeAlias = 'CdnPublicKey'
AnyChannelAdminLogEvent: TypeAlias = 'ChannelAdminLogEvent'
AnyChannelAdminLogEventAction: TypeAlias = Union['ChannelAdminLogEventActionChangeAbout', 'ChannelAdminLogEventActionChangeAvailableReactions', 'ChannelAdminLogEventActionChangeEmojiStatus', 'ChannelAdminLogEventActionChangeEmojiStickerSet', 'ChannelAdminLogEventActionChangeHistoryTTL', 'ChannelAdminLogEventActionChangeLinkedChat', 'ChannelAdminLogEventActionChangeLocation', 'ChannelAdminLogEventActionChangePeerColor', 'ChannelAdminLogEventActionChangePhoto', 'ChannelAdminLogEventActionChangeProfilePeerColor', 'ChannelAdminLogEventActionChangeStickerSet', 'ChannelAdminLogEventActionChangeTitle', 'ChannelAdminLogEventActionChangeUsername', 'ChannelAdminLogEventActionChangeUsernames', 'ChannelAdminLogEventActionChangeWallpaper', 'ChannelAdminLogEventActionCreateTopic', 'ChannelAdminLogEventActionDefaultBannedRights', 'ChannelAdminLogEventActionDeleteMessage', 'ChannelAdminLogEventActionDeleteTopic', 'ChannelAdminLogEventActionDiscardGroupCall', 'ChannelAdminLogEventActionEditMessage', 'ChannelAdminLogEventActionEditTopic', 'ChannelAdminLogEventActionExportedInviteDelete', 'ChannelAdminLogEventActionExportedInviteEdit', 'ChannelAdminLogEventActionExportedInviteRevoke', 'ChannelAdminLogEventActionParticipantEditRank', 'ChannelAdminLogEventActionParticipantInvite', 'ChannelAdminLogEventActionParticipantJoin', 'ChannelAdminLogEventActionParticipantJoinByInvite', 'ChannelAdminLogEventActionParticipantJoinByRequest', 'ChannelAdminLogEventActionParticipantLeave', 'ChannelAdminLogEventActionParticipantMute', 'ChannelAdminLogEventActionParticipantSubExtend', 'ChannelAdminLogEventActionParticipantToggleAdmin', 'ChannelAdminLogEventActionParticipantToggleBan', 'ChannelAdminLogEventActionParticipantUnmute', 'ChannelAdminLogEventActionParticipantVolume', 'ChannelAdminLogEventActionPinTopic', 'ChannelAdminLogEventActionSendMessage', 'ChannelAdminLogEventActionStartGroupCall', 'ChannelAdminLogEventActionStopPoll', 'ChannelAdminLogEventActionToggleAntiSpam', 'ChannelAdminLogEventActionToggleAutotranslation', 'ChannelAdminLogEventActionToggleForum', 'ChannelAdminLogEventActionToggleGroupCallSetting', 'ChannelAdminLogEventActionToggleInvites', 'ChannelAdminLogEventActionToggleNoForwards', 'ChannelAdminLogEventActionTogglePreHistoryHidden', 'ChannelAdminLogEventActionToggleSignatureProfiles', 'ChannelAdminLogEventActionToggleSignatures', 'ChannelAdminLogEventActionToggleSlowMode', 'ChannelAdminLogEventActionUpdatePinned']
AnyChannelAdminLogEventsFilter: TypeAlias = 'ChannelAdminLogEventsFilter'
AnyChannelLocation: TypeAlias = Union['ChannelLocation', 'ChannelLocationEmpty']
AnyChannelMessagesFilter: TypeAlias = Union['ChannelMessagesFilter', 'ChannelMessagesFilterEmpty']
AnyChannelParticipant: TypeAlias = Union['ChannelParticipant', 'ChannelParticipantAdmin', 'ChannelParticipantBanned', 'ChannelParticipantCreator', 'ChannelParticipantLeft', 'ChannelParticipantSelf']
AnyChannelParticipantsFilter: TypeAlias = Union['ChannelParticipantsAdmins', 'ChannelParticipantsBanned', 'ChannelParticipantsBots', 'ChannelParticipantsContacts', 'ChannelParticipantsKicked', 'ChannelParticipantsMentions', 'ChannelParticipantsRecent', 'ChannelParticipantsSearch']
AnyChannelsAdminLogResults: TypeAlias = 'ChannelsAdminLogResults'
AnyChannelsChannelParticipant: TypeAlias = 'ChannelsChannelParticipant'
AnyChannelsChannelParticipants: TypeAlias = Union['ChannelsChannelParticipants', 'ChannelsChannelParticipantsNotModified']
AnyChannelsSendAsPeers: TypeAlias = 'ChannelsSendAsPeers'
AnyChannelsSponsoredMessageReportResult: TypeAlias = Union['ChannelsSponsoredMessageReportResultAdsHidden', 'ChannelsSponsoredMessageReportResultChooseOption', 'ChannelsSponsoredMessageReportResultReported']
AnyChat: TypeAlias = Union['Channel', 'ChannelForbidden', 'Chat', 'ChatEmpty', 'ChatForbidden']
AnyChatAdminRights: TypeAlias = 'ChatAdminRights'
AnyChatAdminWithInvites: TypeAlias = 'ChatAdminWithInvites'
AnyChatBannedRights: TypeAlias = 'ChatBannedRights'
AnyChatFull: TypeAlias = Union['ChannelFull', 'ChatFull']
AnyChatInvite: TypeAlias = Union['ChatInvite', 'ChatInviteAlready', 'ChatInvitePeek']
AnyChatInviteImporter: TypeAlias = 'ChatInviteImporter'
AnyChatOnlines: TypeAlias = 'ChatOnlines'
AnyChatParticipant: TypeAlias = Union['ChatParticipant', 'ChatParticipantAdmin', 'ChatParticipantCreator']
AnyChatParticipants: TypeAlias = Union['ChatParticipants', 'ChatParticipantsForbidden']
AnyChatPhoto: TypeAlias = Union['ChatPhoto', 'ChatPhotoEmpty']
AnyChatReactions: TypeAlias = Union['ChatReactionsAll', 'ChatReactionsNone', 'ChatReactionsSome']
AnyChatTheme: TypeAlias = Union['ChatTheme', 'ChatThemeUniqueGift']
AnyChatlistsChatlistInvite: TypeAlias = Union['ChatlistsChatlistInvite', 'ChatlistsChatlistInviteAlready']
AnyChatlistsChatlistUpdates: TypeAlias = 'ChatlistsChatlistUpdates'
AnyChatlistsExportedChatlistInvite: TypeAlias = 'ChatlistsExportedChatlistInvite'
AnyChatlistsExportedInvites: TypeAlias = 'ChatlistsExportedInvites'
AnyCodeSettings: TypeAlias = 'CodeSettings'
AnyConfig: TypeAlias = 'Config'
AnyConnectedBot: TypeAlias = 'ConnectedBot'
AnyConnectedBotStarRef: TypeAlias = 'ConnectedBotStarRef'
AnyContact: TypeAlias = 'Contact'
AnyContactBirthday: TypeAlias = 'ContactBirthday'
AnyContactStatus: TypeAlias = 'ContactStatus'
AnyContactsBlocked: TypeAlias = Union['ContactsBlocked', 'ContactsBlockedSlice']
AnyContactsContactBirthdays: TypeAlias = 'ContactsContactBirthdays'
AnyContactsContacts: TypeAlias = Union['ContactsContacts', 'ContactsContactsNotModified']
AnyContactsFound: TypeAlias = 'ContactsFound'
AnyContactsImportedContacts: TypeAlias = 'ContactsImportedContacts'
AnyContactsResolvedPeer: TypeAlias = 'ContactsResolvedPeer'
AnyContactsSponsoredPeers: TypeAlias = Union['ContactsSponsoredPeers', 'ContactsSponsoredPeersEmpty']
AnyContactsTopPeers: TypeAlias = Union['ContactsTopPeers', 'ContactsTopPeersDisabled', 'ContactsTopPeersNotModified']
AnyDataJSON: TypeAlias = 'DataJSON'
AnyDcOption: TypeAlias = 'DcOption'
AnyDefaultHistoryTTL: TypeAlias = 'DefaultHistoryTTL'
AnyDialog: TypeAlias = Union['Dialog', 'DialogFolder']
AnyDialogFilter: TypeAlias = Union['DialogFilter', 'DialogFilterChatlist', 'DialogFilterDefault']
AnyDialogFilterSuggested: TypeAlias = 'DialogFilterSuggested'
AnyDialogPeer: TypeAlias = Union['DialogPeer', 'DialogPeerFolder']
AnyDisallowedGiftsSettings: TypeAlias = 'DisallowedGiftsSettings'
AnyDocument: TypeAlias = Union['Document', 'DocumentEmpty']
AnyDocumentAttribute: TypeAlias = Union['DocumentAttributeAnimated', 'DocumentAttributeAudio', 'DocumentAttributeCustomEmoji', 'DocumentAttributeFilename', 'DocumentAttributeHasStickers', 'DocumentAttributeImageSize', 'DocumentAttributeSticker', 'DocumentAttributeVideo']
AnyDraftMessage: TypeAlias = Union['DraftMessage', 'DraftMessageEmpty']
AnyEmailVerification: TypeAlias = Union['EmailVerificationApple', 'EmailVerificationCode', 'EmailVerificationGoogle']
AnyEmailVerifyPurpose: TypeAlias = Union['EmailVerifyPurposeLoginChange', 'EmailVerifyPurposeLoginSetup', 'EmailVerifyPurposePassport']
AnyEmojiGroup: TypeAlias = Union['EmojiGroup', 'EmojiGroupGreeting', 'EmojiGroupPremium']
AnyEmojiKeyword: TypeAlias = Union['EmojiKeyword', 'EmojiKeywordDeleted']
AnyEmojiKeywordsDifference: TypeAlias = 'EmojiKeywordsDifference'
AnyEmojiLanguage: TypeAlias = 'EmojiLanguage'
AnyEmojiList: TypeAlias = Union['EmojiList', 'EmojiListNotModified']
AnyEmojiStatus: TypeAlias = Union['EmojiStatus', 'EmojiStatusCollectible', 'EmojiStatusEmpty', 'InputEmojiStatusCollectible']
AnyEmojiURL: TypeAlias = 'EmojiURL'
AnyEncryptedChat: TypeAlias = Union['EncryptedChat', 'EncryptedChatDiscarded', 'EncryptedChatEmpty', 'EncryptedChatRequested', 'EncryptedChatWaiting']
AnyEncryptedFile: TypeAlias = Union['EncryptedFile', 'EncryptedFileEmpty']
AnyEncryptedMessage: TypeAlias = Union['EncryptedMessage', 'EncryptedMessageService']
AnyError: TypeAlias = 'Error'
AnyExportedChatInvite: TypeAlias = Union['ChatInviteExported', 'ChatInvitePublicJoinRequests']
AnyExportedChatlistInvite: TypeAlias = 'ExportedChatlistInvite'
AnyExportedContactToken: TypeAlias = 'ExportedContactToken'
AnyExportedMessageLink: TypeAlias = 'ExportedMessageLink'
AnyExportedStoryLink: TypeAlias = 'ExportedStoryLink'
AnyFactCheck: TypeAlias = 'FactCheck'
AnyFileHash: TypeAlias = 'FileHash'
AnyFolder: TypeAlias = 'Folder'
AnyFolderPeer: TypeAlias = 'FolderPeer'
AnyForumTopic: TypeAlias = Union['ForumTopic', 'ForumTopicDeleted']
AnyFoundStory: TypeAlias = 'FoundStory'
AnyFragmentCollectibleInfo: TypeAlias = 'FragmentCollectibleInfo'
AnyGame: TypeAlias = 'Game'
AnyGeoPoint: TypeAlias = Union['GeoPoint', 'GeoPointEmpty']
AnyGeoPointAddress: TypeAlias = 'GeoPointAddress'
AnyGlobalPrivacySettings: TypeAlias = 'GlobalPrivacySettings'
AnyGroupCall: TypeAlias = Union['GroupCall', 'GroupCallDiscarded']
AnyGroupCallDonor: TypeAlias = 'GroupCallDonor'
AnyGroupCallMessage: TypeAlias = 'GroupCallMessage'
AnyGroupCallParticipant: TypeAlias = 'GroupCallParticipant'
AnyGroupCallParticipantVideo: TypeAlias = 'GroupCallParticipantVideo'
AnyGroupCallParticipantVideoSourceGroup: TypeAlias = 'GroupCallParticipantVideoSourceGroup'
AnyGroupCallStreamChannel: TypeAlias = 'GroupCallStreamChannel'
AnyHelpAppConfig: TypeAlias = Union['HelpAppConfig', 'HelpAppConfigNotModified']
AnyHelpAppUpdate: TypeAlias = Union['HelpAppUpdate', 'HelpNoAppUpdate']
AnyHelpCountriesList: TypeAlias = Union['HelpCountriesList', 'HelpCountriesListNotModified']
AnyHelpCountry: TypeAlias = 'HelpCountry'
AnyHelpCountryCode: TypeAlias = 'HelpCountryCode'
AnyHelpDeepLinkInfo: TypeAlias = Union['HelpDeepLinkInfo', 'HelpDeepLinkInfoEmpty']
AnyHelpInviteText: TypeAlias = 'HelpInviteText'
AnyHelpPassportConfig: TypeAlias = Union['HelpPassportConfig', 'HelpPassportConfigNotModified']
AnyHelpPeerColorOption: TypeAlias = 'HelpPeerColorOption'
AnyHelpPeerColorSet: TypeAlias = Union['HelpPeerColorProfileSet', 'HelpPeerColorSet']
AnyHelpPeerColors: TypeAlias = Union['HelpPeerColors', 'HelpPeerColorsNotModified']
AnyHelpPremiumPromo: TypeAlias = 'HelpPremiumPromo'
AnyHelpPromoData: TypeAlias = Union['HelpPromoData', 'HelpPromoDataEmpty']
AnyHelpRecentMeUrls: TypeAlias = 'HelpRecentMeUrls'
AnyHelpSupport: TypeAlias = 'HelpSupport'
AnyHelpSupportName: TypeAlias = 'HelpSupportName'
AnyHelpTermsOfService: TypeAlias = 'HelpTermsOfService'
AnyHelpTermsOfServiceUpdate: TypeAlias = Union['HelpTermsOfServiceUpdate', 'HelpTermsOfServiceUpdateEmpty']
AnyHelpTimezonesList: TypeAlias = Union['HelpTimezonesList', 'HelpTimezonesListNotModified']
AnyHelpUserInfo: TypeAlias = Union['HelpUserInfo', 'HelpUserInfoEmpty']
AnyHighScore: TypeAlias = 'HighScore'
AnyImportedContact: TypeAlias = 'ImportedContact'
AnyInlineBotSwitchPM: TypeAlias = 'InlineBotSwitchPM'
AnyInlineBotWebView: TypeAlias = 'InlineBotWebView'
AnyInlineQueryPeerType: TypeAlias = Union['InlineQueryPeerTypeBotPM', 'InlineQueryPeerTypeBroadcast', 'InlineQueryPeerTypeChat', 'InlineQueryPeerTypeMegagroup', 'InlineQueryPeerTypePM', 'InlineQueryPeerTypeSameBotPM']
AnyInputAppEvent: TypeAlias = 'InputAppEvent'
AnyInputBotApp: TypeAlias = Union['InputBotAppID', 'InputBotAppShortName']
AnyInputBotInlineMessage: TypeAlias = Union['InputBotInlineMessageGame', 'InputBotInlineMessageMediaAuto', 'InputBotInlineMessageMediaContact', 'InputBotInlineMessageMediaGeo', 'InputBotInlineMessageMediaInvoice', 'InputBotInlineMessageMediaVenue', 'InputBotInlineMessageMediaWebPage', 'InputBotInlineMessageText']
AnyInputBotInlineMessageID: TypeAlias = Union['InputBotInlineMessageID', 'InputBotInlineMessageID64']
AnyInputBotInlineResult: TypeAlias = Union['InputBotInlineResult', 'InputBotInlineResultDocument', 'InputBotInlineResultGame', 'InputBotInlineResultPhoto']
AnyInputBusinessAwayMessage: TypeAlias = 'InputBusinessAwayMessage'
AnyInputBusinessBotRecipients: TypeAlias = 'InputBusinessBotRecipients'
AnyInputBusinessChatLink: TypeAlias = 'InputBusinessChatLink'
AnyInputBusinessGreetingMessage: TypeAlias = 'InputBusinessGreetingMessage'
AnyInputBusinessIntro: TypeAlias = 'InputBusinessIntro'
AnyInputBusinessRecipients: TypeAlias = 'InputBusinessRecipients'
AnyInputChannel: TypeAlias = Union['InputChannel', 'InputChannelEmpty', 'InputChannelFromMessage']
AnyInputChatPhoto: TypeAlias = Union['InputChatPhoto', 'InputChatPhotoEmpty', 'InputChatUploadedPhoto']
AnyInputChatTheme: TypeAlias = Union['InputChatTheme', 'InputChatThemeEmpty', 'InputChatThemeUniqueGift']
AnyInputChatlist: TypeAlias = 'InputChatlistDialogFilter'
AnyInputCheckPasswordSRP: TypeAlias = Union['InputCheckPasswordEmpty', 'InputCheckPasswordSRP']
AnyInputClientProxy: TypeAlias = 'InputClientProxy'
AnyInputCollectible: TypeAlias = Union['InputCollectiblePhone', 'InputCollectibleUsername']
AnyInputContact: TypeAlias = 'InputPhoneContact'
AnyInputDialogPeer: TypeAlias = Union['InputDialogPeer', 'InputDialogPeerFolder']
AnyInputDocument: TypeAlias = Union['InputDocument', 'InputDocumentEmpty']
AnyInputEncryptedChat: TypeAlias = 'InputEncryptedChat'
AnyInputEncryptedFile: TypeAlias = Union['InputEncryptedFile', 'InputEncryptedFileBigUploaded', 'InputEncryptedFileEmpty', 'InputEncryptedFileUploaded']
AnyInputFile: TypeAlias = Union['InputFile', 'InputFileBig', 'InputFileStoryDocument']
AnyInputFileLocation: TypeAlias = Union['InputDocumentFileLocation', 'InputEncryptedFileLocation', 'InputFileLocation', 'InputGroupCallStream', 'InputPeerPhotoFileLocation', 'InputPhotoFileLocation', 'InputPhotoLegacyFileLocation', 'InputSecureFileLocation', 'InputStickerSetThumb', 'InputTakeoutFileLocation']
AnyInputFolderPeer: TypeAlias = 'InputFolderPeer'
AnyInputGame: TypeAlias = Union['InputGameID', 'InputGameShortName']
AnyInputGeoPoint: TypeAlias = Union['InputGeoPoint', 'InputGeoPointEmpty']
AnyInputGroupCall: TypeAlias = Union['InputGroupCall', 'InputGroupCallInviteMessage', 'InputGroupCallSlug']
AnyInputInvoice: TypeAlias = Union['InputInvoiceBusinessBotTransferStars', 'InputInvoiceChatInviteSubscription', 'InputInvoiceMessage', 'InputInvoicePremiumAuthCode', 'InputInvoicePremiumGiftCode', 'InputInvoicePremiumGiftStars', 'InputInvoiceSlug', 'InputInvoiceStarGift', 'InputInvoiceStarGiftAuctionBid', 'InputInvoiceStarGiftDropOriginalDetails', 'InputInvoiceStarGiftPrepaidUpgrade', 'InputInvoiceStarGiftResale', 'InputInvoiceStarGiftTransfer', 'InputInvoiceStarGiftUpgrade', 'InputInvoiceStars']
AnyInputMedia: TypeAlias = Union['InputMediaContact', 'InputMediaDice', 'InputMediaDocument', 'InputMediaDocumentExternal', 'InputMediaEmpty', 'InputMediaGame', 'InputMediaGeoLive', 'InputMediaGeoPoint', 'InputMediaInvoice', 'InputMediaPaidMedia', 'InputMediaPhoto', 'InputMediaPhotoExternal', 'InputMediaPoll', 'InputMediaStakeDice', 'InputMediaStory', 'InputMediaTodo', 'InputMediaUploadedDocument', 'InputMediaUploadedPhoto', 'InputMediaVenue', 'InputMediaWebPage']
AnyInputMessage: TypeAlias = Union['InputMessageCallbackQuery', 'InputMessageID', 'InputMessagePinned', 'InputMessageReplyTo']
AnyInputNotifyPeer: TypeAlias = Union['InputNotifyBroadcasts', 'InputNotifyChats', 'InputNotifyForumTopic', 'InputNotifyPeer', 'InputNotifyUsers']
AnyInputPasskeyCredential: TypeAlias = Union['InputPasskeyCredentialFirebasePNV', 'InputPasskeyCredentialPublicKey']
AnyInputPasskeyResponse: TypeAlias = Union['InputPasskeyResponseLogin', 'InputPasskeyResponseRegister']
AnyInputPaymentCredentials: TypeAlias = Union['InputPaymentCredentials', 'InputPaymentCredentialsApplePay', 'InputPaymentCredentialsGooglePay', 'InputPaymentCredentialsSaved']
AnyInputPeer: TypeAlias = Union['InputPeerChannel', 'InputPeerChannelFromMessage', 'InputPeerChat', 'InputPeerEmpty', 'InputPeerSelf', 'InputPeerUser', 'InputPeerUserFromMessage']
AnyInputPeerNotifySettings: TypeAlias = 'InputPeerNotifySettings'
AnyInputPhoneCall: TypeAlias = 'InputPhoneCall'
AnyInputPhoto: TypeAlias = Union['InputPhoto', 'InputPhotoEmpty']
AnyInputPrivacyKey: TypeAlias = Union['InputPrivacyKeyAbout', 'InputPrivacyKeyAddedByPhone', 'InputPrivacyKeyBirthday', 'InputPrivacyKeyChatInvite', 'InputPrivacyKeyForwards', 'InputPrivacyKeyNoPaidMessages', 'InputPrivacyKeyPhoneCall', 'InputPrivacyKeyPhoneNumber', 'InputPrivacyKeyPhoneP2P', 'InputPrivacyKeyProfilePhoto', 'InputPrivacyKeySavedMusic', 'InputPrivacyKeyStarGiftsAutoSave', 'InputPrivacyKeyStatusTimestamp', 'InputPrivacyKeyVoiceMessages']
AnyInputPrivacyRule: TypeAlias = Union['InputPrivacyValueAllowAll', 'InputPrivacyValueAllowBots', 'InputPrivacyValueAllowChatParticipants', 'InputPrivacyValueAllowCloseFriends', 'InputPrivacyValueAllowContacts', 'InputPrivacyValueAllowPremium', 'InputPrivacyValueAllowUsers', 'InputPrivacyValueDisallowAll', 'InputPrivacyValueDisallowBots', 'InputPrivacyValueDisallowChatParticipants', 'InputPrivacyValueDisallowContacts', 'InputPrivacyValueDisallowUsers']
AnyInputQuickReplyShortcut: TypeAlias = Union['InputQuickReplyShortcut', 'InputQuickReplyShortcutId']
AnyInputReplyTo: TypeAlias = Union['InputReplyToMessage', 'InputReplyToMonoForum', 'InputReplyToStory']
AnyInputSavedStarGift: TypeAlias = Union['InputSavedStarGiftChat', 'InputSavedStarGiftSlug', 'InputSavedStarGiftUser']
AnyInputSecureFile: TypeAlias = Union['InputSecureFile', 'InputSecureFileUploaded']
AnyInputSecureValue: TypeAlias = 'InputSecureValue'
AnyInputSingleMedia: TypeAlias = 'InputSingleMedia'
AnyInputStarGiftAuction: TypeAlias = Union['InputStarGiftAuction', 'InputStarGiftAuctionSlug']
AnyInputStarsTransaction: TypeAlias = 'InputStarsTransaction'
AnyInputStickerSet: TypeAlias = Union['InputStickerSetAnimatedEmoji', 'InputStickerSetAnimatedEmojiAnimations', 'InputStickerSetDice', 'InputStickerSetEmojiChannelDefaultStatuses', 'InputStickerSetEmojiDefaultStatuses', 'InputStickerSetEmojiDefaultTopicIcons', 'InputStickerSetEmojiGenericAnimations', 'InputStickerSetEmpty', 'InputStickerSetID', 'InputStickerSetPremiumGifts', 'InputStickerSetShortName', 'InputStickerSetTonGifts']
AnyInputStickerSetItem: TypeAlias = 'InputStickerSetItem'
AnyInputStickeredMedia: TypeAlias = Union['InputStickeredMediaDocument', 'InputStickeredMediaPhoto']
AnyInputStorePaymentPurpose: TypeAlias = Union['InputStorePaymentAuthCode', 'InputStorePaymentGiftPremium', 'InputStorePaymentPremiumGiftCode', 'InputStorePaymentPremiumGiveaway', 'InputStorePaymentPremiumSubscription', 'InputStorePaymentStarsGift', 'InputStorePaymentStarsGiveaway', 'InputStorePaymentStarsTopup']
AnyInputTheme: TypeAlias = Union['InputTheme', 'InputThemeSlug']
AnyInputThemeSettings: TypeAlias = 'InputThemeSettings'
AnyInputUser: TypeAlias = Union['InputUser', 'InputUserEmpty', 'InputUserFromMessage', 'InputUserSelf']
AnyInputWallPaper: TypeAlias = Union['InputWallPaper', 'InputWallPaperNoFile', 'InputWallPaperSlug']
AnyInputWebDocument: TypeAlias = 'InputWebDocument'
AnyInputWebFileLocation: TypeAlias = Union['InputWebFileAudioAlbumThumbLocation', 'InputWebFileGeoPointLocation', 'InputWebFileLocation']
AnyInvoice: TypeAlias = 'Invoice'
AnyJSONObjectValue: TypeAlias = 'JsonObjectValue'
AnyJSONValue: TypeAlias = Union['JsonArray', 'JsonBool', 'JsonNull', 'JsonNumber', 'JsonObject', 'JsonString']
AnyKeyboardButton: TypeAlias = Union['InputKeyboardButtonRequestPeer', 'InputKeyboardButtonUrlAuth', 'InputKeyboardButtonUserProfile', 'KeyboardButton', 'KeyboardButtonBuy', 'KeyboardButtonCallback', 'KeyboardButtonCopy', 'KeyboardButtonGame', 'KeyboardButtonRequestGeoLocation', 'KeyboardButtonRequestPeer', 'KeyboardButtonRequestPhone', 'KeyboardButtonRequestPoll', 'KeyboardButtonSimpleWebView', 'KeyboardButtonSwitchInline', 'KeyboardButtonUrl', 'KeyboardButtonUrlAuth', 'KeyboardButtonUserProfile', 'KeyboardButtonWebView']
AnyKeyboardButtonRow: TypeAlias = 'KeyboardButtonRow'
AnyKeyboardButtonStyle: TypeAlias = 'KeyboardButtonStyle'
AnyLabeledPrice: TypeAlias = 'LabeledPrice'
AnyLangPackDifference: TypeAlias = 'LangPackDifference'
AnyLangPackLanguage: TypeAlias = 'LangPackLanguage'
AnyLangPackString: TypeAlias = Union['LangPackString', 'LangPackStringDeleted', 'LangPackStringPluralized']
AnyMaskCoords: TypeAlias = 'MaskCoords'
AnyMediaArea: TypeAlias = Union['InputMediaAreaChannelPost', 'InputMediaAreaVenue', 'MediaAreaChannelPost', 'MediaAreaGeoPoint', 'MediaAreaStarGift', 'MediaAreaSuggestedReaction', 'MediaAreaUrl', 'MediaAreaVenue', 'MediaAreaWeather']
AnyMediaAreaCoordinates: TypeAlias = 'MediaAreaCoordinates'
AnyMessage: TypeAlias = Union['Message', 'MessageEmpty', 'MessageService']
AnyMessageAction: TypeAlias = Union['MessageActionBoostApply', 'MessageActionBotAllowed', 'MessageActionChangeCreator', 'MessageActionChannelCreate', 'MessageActionChannelMigrateFrom', 'MessageActionChatAddUser', 'MessageActionChatCreate', 'MessageActionChatDeletePhoto', 'MessageActionChatDeleteUser', 'MessageActionChatEditPhoto', 'MessageActionChatEditTitle', 'MessageActionChatJoinedByLink', 'MessageActionChatJoinedByRequest', 'MessageActionChatMigrateTo', 'MessageActionConferenceCall', 'MessageActionContactSignUp', 'MessageActionCustomAction', 'MessageActionEmpty', 'MessageActionGameScore', 'MessageActionGeoProximityReached', 'MessageActionGiftCode', 'MessageActionGiftPremium', 'MessageActionGiftStars', 'MessageActionGiftTon', 'MessageActionGiveawayLaunch', 'MessageActionGiveawayResults', 'MessageActionGroupCall', 'MessageActionGroupCallScheduled', 'MessageActionHistoryClear', 'MessageActionInviteToGroupCall', 'MessageActionNewCreatorPending', 'MessageActionNoForwardsRequest', 'MessageActionNoForwardsToggle', 'MessageActionPaidMessagesPrice', 'MessageActionPaidMessagesRefunded', 'MessageActionPaymentRefunded', 'MessageActionPaymentSent', 'MessageActionPaymentSentMe', 'MessageActionPhoneCall', 'MessageActionPinMessage', 'MessageActionPrizeStars', 'MessageActionRequestedPeer', 'MessageActionRequestedPeerSentMe', 'MessageActionScreenshotTaken', 'MessageActionSecureValuesSent', 'MessageActionSecureValuesSentMe', 'MessageActionSetChatTheme', 'MessageActionSetChatWallPaper', 'MessageActionSetMessagesTTL', 'MessageActionStarGift', 'MessageActionStarGiftPurchaseOffer', 'MessageActionStarGiftPurchaseOfferDeclined', 'MessageActionStarGiftUnique', 'MessageActionSuggestBirthday', 'MessageActionSuggestProfilePhoto', 'MessageActionSuggestedPostApproval', 'MessageActionSuggestedPostRefund', 'MessageActionSuggestedPostSuccess', 'MessageActionTodoAppendTasks', 'MessageActionTodoCompletions', 'MessageActionTopicCreate', 'MessageActionTopicEdit', 'MessageActionWebViewDataSent', 'MessageActionWebViewDataSentMe']
AnyMessageEntity: TypeAlias = Union['InputMessageEntityMentionName', 'MessageEntityBankCard', 'MessageEntityBlockquote', 'MessageEntityBold', 'MessageEntityBotCommand', 'MessageEntityCashtag', 'MessageEntityCode', 'MessageEntityCustomEmoji', 'MessageEntityEmail', 'MessageEntityFormattedDate', 'MessageEntityHashtag', 'MessageEntityItalic', 'MessageEntityMention', 'MessageEntityMentionName', 'MessageEntityPhone', 'MessageEntityPre', 'MessageEntitySpoiler', 'MessageEntityStrike', 'MessageEntityTextUrl', 'MessageEntityUnderline', 'MessageEntityUnknown', 'MessageEntityUrl']
AnyMessageExtendedMedia: TypeAlias = Union['MessageExtendedMedia', 'MessageExtendedMediaPreview']
AnyMessageFwdHeader: TypeAlias = 'MessageFwdHeader'
AnyMessageMedia: TypeAlias = Union['MessageMediaContact', 'MessageMediaDice', 'MessageMediaDocument', 'MessageMediaEmpty', 'MessageMediaGame', 'MessageMediaGeo', 'MessageMediaGeoLive', 'MessageMediaGiveaway', 'MessageMediaGiveawayResults', 'MessageMediaInvoice', 'MessageMediaPaidMedia', 'MessageMediaPhoto', 'MessageMediaPoll', 'MessageMediaStory', 'MessageMediaToDo', 'MessageMediaUnsupported', 'MessageMediaVenue', 'MessageMediaVideoStream', 'MessageMediaWebPage']
AnyMessagePeerReaction: TypeAlias = 'MessagePeerReaction'
AnyMessagePeerVote: TypeAlias = Union['MessagePeerVote', 'MessagePeerVoteInputOption', 'MessagePeerVoteMultiple']
AnyMessageRange: TypeAlias = 'MessageRange'
AnyMessageReactions: TypeAlias = 'MessageReactions'
AnyMessageReactor: TypeAlias = 'MessageReactor'
AnyMessageReplies: TypeAlias = 'MessageReplies'
AnyMessageReplyHeader: TypeAlias = Union['MessageReplyHeader', 'MessageReplyStoryHeader']
AnyMessageReportOption: TypeAlias = 'MessageReportOption'
AnyMessageViews: TypeAlias = 'MessageViews'
AnyMessagesAffectedFoundMessages: TypeAlias = 'MessagesAffectedFoundMessages'
AnyMessagesAffectedHistory: TypeAlias = 'MessagesAffectedHistory'
AnyMessagesAffectedMessages: TypeAlias = 'MessagesAffectedMessages'
AnyMessagesAllStickers: TypeAlias = Union['MessagesAllStickers', 'MessagesAllStickersNotModified']
AnyMessagesArchivedStickers: TypeAlias = 'MessagesArchivedStickers'
AnyMessagesAvailableEffects: TypeAlias = Union['MessagesAvailableEffects', 'MessagesAvailableEffectsNotModified']
AnyMessagesAvailableReactions: TypeAlias = Union['MessagesAvailableReactions', 'MessagesAvailableReactionsNotModified']
AnyMessagesBotApp: TypeAlias = 'MessagesBotApp'
AnyMessagesBotCallbackAnswer: TypeAlias = 'MessagesBotCallbackAnswer'
AnyMessagesBotPreparedInlineMessage: TypeAlias = 'MessagesBotPreparedInlineMessage'
AnyMessagesBotResults: TypeAlias = 'MessagesBotResults'
AnyMessagesChatAdminsWithInvites: TypeAlias = 'MessagesChatAdminsWithInvites'
AnyMessagesChatFull: TypeAlias = 'MessagesChatFull'
AnyMessagesChatInviteImporters: TypeAlias = 'MessagesChatInviteImporters'
AnyMessagesChats: TypeAlias = Union['MessagesChats', 'MessagesChatsSlice']
AnyMessagesCheckedHistoryImportPeer: TypeAlias = 'MessagesCheckedHistoryImportPeer'
AnyMessagesDhConfig: TypeAlias = Union['MessagesDhConfig', 'MessagesDhConfigNotModified']
AnyMessagesDialogFilters: TypeAlias = 'MessagesDialogFilters'
AnyMessagesDialogs: TypeAlias = Union['MessagesDialogs', 'MessagesDialogsNotModified', 'MessagesDialogsSlice']
AnyMessagesDiscussionMessage: TypeAlias = 'MessagesDiscussionMessage'
AnyMessagesEmojiGameInfo: TypeAlias = Union['MessagesEmojiGameDiceInfo', 'MessagesEmojiGameUnavailable']
AnyMessagesEmojiGameOutcome: TypeAlias = 'MessagesEmojiGameOutcome'
AnyMessagesEmojiGroups: TypeAlias = Union['MessagesEmojiGroups', 'MessagesEmojiGroupsNotModified']
AnyMessagesExportedChatInvite: TypeAlias = Union['MessagesExportedChatInvite', 'MessagesExportedChatInviteReplaced']
AnyMessagesExportedChatInvites: TypeAlias = 'MessagesExportedChatInvites'
AnyMessagesFavedStickers: TypeAlias = Union['MessagesFavedStickers', 'MessagesFavedStickersNotModified']
AnyMessagesFeaturedStickers: TypeAlias = Union['MessagesFeaturedStickers', 'MessagesFeaturedStickersNotModified']
AnyMessagesFilter: TypeAlias = Union['InputMessagesFilterChatPhotos', 'InputMessagesFilterContacts', 'InputMessagesFilterDocument', 'InputMessagesFilterEmpty', 'InputMessagesFilterGeo', 'InputMessagesFilterGif', 'InputMessagesFilterMusic', 'InputMessagesFilterMyMentions', 'InputMessagesFilterPhoneCalls', 'InputMessagesFilterPhotoVideo', 'InputMessagesFilterPhotos', 'InputMessagesFilterPinned', 'InputMessagesFilterRoundVideo', 'InputMessagesFilterRoundVoice', 'InputMessagesFilterUrl', 'InputMessagesFilterVideo', 'InputMessagesFilterVoice']
AnyMessagesForumTopics: TypeAlias = 'MessagesForumTopics'
AnyMessagesFoundStickerSets: TypeAlias = Union['MessagesFoundStickerSets', 'MessagesFoundStickerSetsNotModified']
AnyMessagesFoundStickers: TypeAlias = Union['MessagesFoundStickers', 'MessagesFoundStickersNotModified']
AnyMessagesHighScores: TypeAlias = 'MessagesHighScores'
AnyMessagesHistoryImport: TypeAlias = 'MessagesHistoryImport'
AnyMessagesHistoryImportParsed: TypeAlias = 'MessagesHistoryImportParsed'
AnyMessagesInactiveChats: TypeAlias = 'MessagesInactiveChats'
AnyMessagesInvitedUsers: TypeAlias = 'MessagesInvitedUsers'
AnyMessagesMessageEditData: TypeAlias = 'MessagesMessageEditData'
AnyMessagesMessageReactionsList: TypeAlias = 'MessagesMessageReactionsList'
AnyMessagesMessageViews: TypeAlias = 'MessagesMessageViews'
AnyMessagesMessages: TypeAlias = Union['MessagesChannelMessages', 'MessagesMessages', 'MessagesMessagesNotModified', 'MessagesMessagesSlice']
AnyMessagesMyStickers: TypeAlias = 'MessagesMyStickers'
AnyMessagesPeerDialogs: TypeAlias = 'MessagesPeerDialogs'
AnyMessagesPeerSettings: TypeAlias = 'MessagesPeerSettings'
AnyMessagesPreparedInlineMessage: TypeAlias = 'MessagesPreparedInlineMessage'
AnyMessagesQuickReplies: TypeAlias = Union['MessagesQuickReplies', 'MessagesQuickRepliesNotModified']
AnyMessagesReactions: TypeAlias = Union['MessagesReactions', 'MessagesReactionsNotModified']
AnyMessagesRecentStickers: TypeAlias = Union['MessagesRecentStickers', 'MessagesRecentStickersNotModified']
AnyMessagesSavedDialogs: TypeAlias = Union['MessagesSavedDialogs', 'MessagesSavedDialogsNotModified', 'MessagesSavedDialogsSlice']
AnyMessagesSavedGifs: TypeAlias = Union['MessagesSavedGifs', 'MessagesSavedGifsNotModified']
AnyMessagesSavedReactionTags: TypeAlias = Union['MessagesSavedReactionTags', 'MessagesSavedReactionTagsNotModified']
AnyMessagesSearchCounter: TypeAlias = 'MessagesSearchCounter'
AnyMessagesSearchResultsCalendar: TypeAlias = 'MessagesSearchResultsCalendar'
AnyMessagesSearchResultsPositions: TypeAlias = 'MessagesSearchResultsPositions'
AnyMessagesSentEncryptedMessage: TypeAlias = Union['MessagesSentEncryptedFile', 'MessagesSentEncryptedMessage']
AnyMessagesSponsoredMessages: TypeAlias = Union['MessagesSponsoredMessages', 'MessagesSponsoredMessagesEmpty']
AnyMessagesStickerSet: TypeAlias = Union['MessagesStickerSet', 'MessagesStickerSetNotModified']
AnyMessagesStickerSetInstallResult: TypeAlias = Union['MessagesStickerSetInstallResultArchive', 'MessagesStickerSetInstallResultSuccess']
AnyMessagesStickers: TypeAlias = Union['MessagesStickers', 'MessagesStickersNotModified']
AnyMessagesTranscribedAudio: TypeAlias = 'MessagesTranscribedAudio'
AnyMessagesTranslatedText: TypeAlias = 'MessagesTranslateResult'
AnyMessagesVotesList: TypeAlias = 'MessagesVotesList'
AnyMessagesWebPage: TypeAlias = 'MessagesWebPage'
AnyMessagesWebPagePreview: TypeAlias = 'MessagesWebPagePreview'
AnyMissingInvitee: TypeAlias = 'MissingInvitee'
AnyMyBoost: TypeAlias = 'MyBoost'
AnyNearestDc: TypeAlias = 'NearestDc'
AnyNotificationSound: TypeAlias = Union['NotificationSoundDefault', 'NotificationSoundLocal', 'NotificationSoundNone', 'NotificationSoundRingtone']
AnyNotifyPeer: TypeAlias = Union['NotifyBroadcasts', 'NotifyChats', 'NotifyForumTopic', 'NotifyPeer', 'NotifyUsers']
AnyOutboxReadDate: TypeAlias = 'OutboxReadDate'
AnyPage: TypeAlias = 'Page'
AnyPageBlock: TypeAlias = Union['PageBlockAnchor', 'PageBlockAudio', 'PageBlockAuthorDate', 'PageBlockBlockquote', 'PageBlockChannel', 'PageBlockCollage', 'PageBlockCover', 'PageBlockDetails', 'PageBlockDivider', 'PageBlockEmbed', 'PageBlockEmbedPost', 'PageBlockFooter', 'PageBlockHeader', 'PageBlockKicker', 'PageBlockList', 'PageBlockMap', 'PageBlockOrderedList', 'PageBlockParagraph', 'PageBlockPhoto', 'PageBlockPreformatted', 'PageBlockPullquote', 'PageBlockRelatedArticles', 'PageBlockSlideshow', 'PageBlockSubheader', 'PageBlockSubtitle', 'PageBlockTable', 'PageBlockTitle', 'PageBlockUnsupported', 'PageBlockVideo']
AnyPageCaption: TypeAlias = 'PageCaption'
AnyPageListItem: TypeAlias = Union['PageListItemBlocks', 'PageListItemText']
AnyPageListOrderedItem: TypeAlias = Union['PageListOrderedItemBlocks', 'PageListOrderedItemText']
AnyPageRelatedArticle: TypeAlias = 'PageRelatedArticle'
AnyPageTableCell: TypeAlias = 'PageTableCell'
AnyPageTableRow: TypeAlias = 'PageTableRow'
AnyPaidReactionPrivacy: TypeAlias = Union['PaidReactionPrivacyAnonymous', 'PaidReactionPrivacyDefault', 'PaidReactionPrivacyPeer']
AnyPasskey: TypeAlias = 'Passkey'
AnyPasswordKdfAlgo: TypeAlias = Union['PasswordKdfAlgoSHA256SHA256PBKDF2HMACSHA512iter100000SHA256ModPow', 'PasswordKdfAlgoUnknown']
AnyPaymentCharge: TypeAlias = 'PaymentCharge'
AnyPaymentFormMethod: TypeAlias = 'PaymentFormMethod'
AnyPaymentRequestedInfo: TypeAlias = 'PaymentRequestedInfo'
AnyPaymentSavedCredentials: TypeAlias = 'PaymentSavedCredentialsCard'
AnyPaymentsBankCardData: TypeAlias = 'PaymentsBankCardData'
AnyPaymentsCheckCanSendGiftResult: TypeAlias = Union['PaymentsCheckCanSendGiftResultFail', 'PaymentsCheckCanSendGiftResultOk']
AnyPaymentsCheckedGiftCode: TypeAlias = 'PaymentsCheckedGiftCode'
AnyPaymentsConnectedStarRefBots: TypeAlias = 'PaymentsConnectedStarRefBots'
AnyPaymentsExportedInvoice: TypeAlias = 'PaymentsExportedInvoice'
AnyPaymentsGiveawayInfo: TypeAlias = Union['PaymentsGiveawayInfo', 'PaymentsGiveawayInfoResults']
AnyPaymentsPaymentForm: TypeAlias = Union['PaymentsPaymentForm', 'PaymentsPaymentFormStarGift', 'PaymentsPaymentFormStars']
AnyPaymentsPaymentReceipt: TypeAlias = Union['PaymentsPaymentReceipt', 'PaymentsPaymentReceiptStars']
AnyPaymentsPaymentResult: TypeAlias = Union['PaymentsPaymentResult', 'PaymentsPaymentVerificationNeeded']
AnyPaymentsResaleStarGifts: TypeAlias = 'PaymentsResaleStarGifts'
AnyPaymentsSavedInfo: TypeAlias = 'PaymentsSavedInfo'
AnyPaymentsSavedStarGifts: TypeAlias = 'PaymentsSavedStarGifts'
AnyPaymentsStarGiftActiveAuctions: TypeAlias = Union['PaymentsStarGiftActiveAuctions', 'PaymentsStarGiftActiveAuctionsNotModified']
AnyPaymentsStarGiftAuctionAcquiredGifts: TypeAlias = 'PaymentsStarGiftAuctionAcquiredGifts'
AnyPaymentsStarGiftAuctionState: TypeAlias = 'PaymentsStarGiftAuctionState'
AnyPaymentsStarGiftCollections: TypeAlias = Union['PaymentsStarGiftCollections', 'PaymentsStarGiftCollectionsNotModified']
AnyPaymentsStarGiftUpgradeAttributes: TypeAlias = 'PaymentsStarGiftUpgradeAttributes'
AnyPaymentsStarGiftUpgradePreview: TypeAlias = 'PaymentsStarGiftUpgradePreview'
AnyPaymentsStarGiftWithdrawalUrl: TypeAlias = 'PaymentsStarGiftWithdrawalUrl'
AnyPaymentsStarGifts: TypeAlias = Union['PaymentsStarGifts', 'PaymentsStarGiftsNotModified']
AnyPaymentsStarsRevenueAdsAccountUrl: TypeAlias = 'PaymentsStarsRevenueAdsAccountUrl'
AnyPaymentsStarsRevenueStats: TypeAlias = 'PaymentsStarsRevenueStats'
AnyPaymentsStarsRevenueWithdrawalUrl: TypeAlias = 'PaymentsStarsRevenueWithdrawalUrl'
AnyPaymentsStarsStatus: TypeAlias = 'PaymentsStarsStatus'
AnyPaymentsSuggestedStarRefBots: TypeAlias = 'PaymentsSuggestedStarRefBots'
AnyPaymentsUniqueStarGift: TypeAlias = 'PaymentsUniqueStarGift'
AnyPaymentsUniqueStarGiftValueInfo: TypeAlias = 'PaymentsUniqueStarGiftValueInfo'
AnyPaymentsValidatedRequestedInfo: TypeAlias = 'PaymentsValidatedRequestedInfo'
AnyPeer: TypeAlias = Union['PeerChannel', 'PeerChat', 'PeerUser']
AnyPeerBlocked: TypeAlias = 'PeerBlocked'
AnyPeerColor: TypeAlias = Union['InputPeerColorCollectible', 'PeerColor', 'PeerColorCollectible']
AnyPeerLocated: TypeAlias = Union['PeerLocated', 'PeerSelfLocated']
AnyPeerNotifySettings: TypeAlias = 'PeerNotifySettings'
AnyPeerSettings: TypeAlias = 'PeerSettings'
AnyPeerStories: TypeAlias = 'PeerStories'
AnyPendingSuggestion: TypeAlias = 'PendingSuggestion'
AnyPhoneCall: TypeAlias = Union['PhoneCall', 'PhoneCallAccepted', 'PhoneCallDiscarded', 'PhoneCallEmpty', 'PhoneCallRequested', 'PhoneCallWaiting']
AnyPhoneCallDiscardReason: TypeAlias = Union['PhoneCallDiscardReasonBusy', 'PhoneCallDiscardReasonDisconnect', 'PhoneCallDiscardReasonHangup', 'PhoneCallDiscardReasonMigrateConferenceCall', 'PhoneCallDiscardReasonMissed']
AnyPhoneCallProtocol: TypeAlias = 'PhoneCallProtocol'
AnyPhoneConnection: TypeAlias = Union['PhoneConnection', 'PhoneConnectionWebrtc']
AnyPhoneExportedGroupCallInvite: TypeAlias = 'PhoneExportedGroupCallInvite'
AnyPhoneGroupCall: TypeAlias = 'PhoneGroupCall'
AnyPhoneGroupCallStars: TypeAlias = 'PhoneGroupCallStars'
AnyPhoneGroupCallStreamChannels: TypeAlias = 'PhoneGroupCallStreamChannels'
AnyPhoneGroupCallStreamRtmpUrl: TypeAlias = 'PhoneGroupCallStreamRtmpUrl'
AnyPhoneGroupParticipants: TypeAlias = 'PhoneGroupParticipants'
AnyPhoneJoinAsPeers: TypeAlias = 'PhoneJoinAsPeers'
AnyPhonePhoneCall: TypeAlias = 'PhonePhoneCall'
AnyPhoto: TypeAlias = Union['Photo', 'PhotoEmpty']
AnyPhotoSize: TypeAlias = Union['PhotoCachedSize', 'PhotoPathSize', 'PhotoSize', 'PhotoSizeEmpty', 'PhotoSizeProgressive', 'PhotoStrippedSize']
AnyPhotosPhoto: TypeAlias = 'PhotosPhoto'
AnyPhotosPhotos: TypeAlias = Union['PhotosPhotos', 'PhotosPhotosSlice']
AnyPoll: TypeAlias = 'Poll'
AnyPollAnswer: TypeAlias = 'PollAnswer'
AnyPollAnswerVoters: TypeAlias = 'PollAnswerVoters'
AnyPollResults: TypeAlias = 'PollResults'
AnyPopularContact: TypeAlias = 'PopularContact'
AnyPostAddress: TypeAlias = 'PostAddress'
AnyPostInteractionCounters: TypeAlias = Union['PostInteractionCountersMessage', 'PostInteractionCountersStory']
AnyPremiumBoostsList: TypeAlias = 'PremiumBoostsList'
AnyPremiumBoostsStatus: TypeAlias = 'PremiumBoostsStatus'
AnyPremiumGiftCodeOption: TypeAlias = 'PremiumGiftCodeOption'
AnyPremiumMyBoosts: TypeAlias = 'PremiumMyBoosts'
AnyPremiumSubscriptionOption: TypeAlias = 'PremiumSubscriptionOption'
AnyPrepaidGiveaway: TypeAlias = Union['PrepaidGiveaway', 'PrepaidStarsGiveaway']
AnyPrivacyKey: TypeAlias = Union['PrivacyKeyAbout', 'PrivacyKeyAddedByPhone', 'PrivacyKeyBirthday', 'PrivacyKeyChatInvite', 'PrivacyKeyForwards', 'PrivacyKeyNoPaidMessages', 'PrivacyKeyPhoneCall', 'PrivacyKeyPhoneNumber', 'PrivacyKeyPhoneP2P', 'PrivacyKeyProfilePhoto', 'PrivacyKeySavedMusic', 'PrivacyKeyStarGiftsAutoSave', 'PrivacyKeyStatusTimestamp', 'PrivacyKeyVoiceMessages']
AnyPrivacyRule: TypeAlias = Union['PrivacyValueAllowAll', 'PrivacyValueAllowBots', 'PrivacyValueAllowChatParticipants', 'PrivacyValueAllowCloseFriends', 'PrivacyValueAllowContacts', 'PrivacyValueAllowPremium', 'PrivacyValueAllowUsers', 'PrivacyValueDisallowAll', 'PrivacyValueDisallowBots', 'PrivacyValueDisallowChatParticipants', 'PrivacyValueDisallowContacts', 'PrivacyValueDisallowUsers']
AnyProfileTab: TypeAlias = Union['ProfileTabFiles', 'ProfileTabGifs', 'ProfileTabGifts', 'ProfileTabLinks', 'ProfileTabMedia', 'ProfileTabMusic', 'ProfileTabPosts', 'ProfileTabVoice']
AnyPublicForward: TypeAlias = Union['PublicForwardMessage', 'PublicForwardStory']
AnyQuickReply: TypeAlias = 'QuickReply'
AnyReaction: TypeAlias = Union['ReactionCustomEmoji', 'ReactionEmoji', 'ReactionEmpty', 'ReactionPaid']
AnyReactionCount: TypeAlias = 'ReactionCount'
AnyReactionNotificationsFrom: TypeAlias = Union['ReactionNotificationsFromAll', 'ReactionNotificationsFromContacts']
AnyReactionsNotifySettings: TypeAlias = 'ReactionsNotifySettings'
AnyReadParticipantDate: TypeAlias = 'ReadParticipantDate'
AnyReceivedNotifyMessage: TypeAlias = 'ReceivedNotifyMessage'
AnyRecentMeUrl: TypeAlias = Union['RecentMeUrlChat', 'RecentMeUrlChatInvite', 'RecentMeUrlStickerSet', 'RecentMeUrlUnknown', 'RecentMeUrlUser']
AnyRecentStory: TypeAlias = 'RecentStory'
AnyReplyMarkup: TypeAlias = Union['ReplyInlineMarkup', 'ReplyKeyboardForceReply', 'ReplyKeyboardHide', 'ReplyKeyboardMarkup']
AnyReportReason: TypeAlias = Union['InputReportReasonChildAbuse', 'InputReportReasonCopyright', 'InputReportReasonFake', 'InputReportReasonGeoIrrelevant', 'InputReportReasonIllegalDrugs', 'InputReportReasonOther', 'InputReportReasonPersonalDetails', 'InputReportReasonPornography', 'InputReportReasonSpam', 'InputReportReasonViolence']
AnyReportResult: TypeAlias = Union['ReportResultAddComment', 'ReportResultChooseOption', 'ReportResultReported']
AnyRequestPeerType: TypeAlias = Union['RequestPeerTypeBroadcast', 'RequestPeerTypeChat', 'RequestPeerTypeUser']
AnyRequestedPeer: TypeAlias = Union['RequestedPeerChannel', 'RequestedPeerChat', 'RequestedPeerUser']
AnyRequirementToContact: TypeAlias = Union['RequirementToContactEmpty', 'RequirementToContactPaidMessages', 'RequirementToContactPremium']
AnyRestrictionReason: TypeAlias = 'RestrictionReason'
AnyRichText: TypeAlias = Union['TextAnchor', 'TextBold', 'TextConcat', 'TextEmail', 'TextEmpty', 'TextFixed', 'TextImage', 'TextItalic', 'TextMarked', 'TextPhone', 'TextPlain', 'TextStrike', 'TextSubscript', 'TextSuperscript', 'TextUnderline', 'TextUrl']
AnySavedContact: TypeAlias = 'SavedPhoneContact'
AnySavedDialog: TypeAlias = Union['MonoForumDialog', 'SavedDialog']
AnySavedReactionTag: TypeAlias = 'SavedReactionTag'
AnySavedStarGift: TypeAlias = 'SavedStarGift'
AnySearchPostsFlood: TypeAlias = 'SearchPostsFlood'
AnySearchResultsCalendarPeriod: TypeAlias = 'SearchResultsCalendarPeriod'
AnySearchResultsPosition: TypeAlias = 'SearchResultPosition'
AnySecureCredentialsEncrypted: TypeAlias = 'SecureCredentialsEncrypted'
AnySecureData: TypeAlias = 'SecureData'
AnySecureFile: TypeAlias = Union['SecureFile', 'SecureFileEmpty']
AnySecurePasswordKdfAlgo: TypeAlias = Union['SecurePasswordKdfAlgoPBKDF2HMACSHA512iter100000', 'SecurePasswordKdfAlgoSHA512', 'SecurePasswordKdfAlgoUnknown']
AnySecurePlainData: TypeAlias = Union['SecurePlainEmail', 'SecurePlainPhone']
AnySecureRequiredType: TypeAlias = Union['SecureRequiredType', 'SecureRequiredTypeOneOf']
AnySecureSecretSettings: TypeAlias = 'SecureSecretSettings'
AnySecureValue: TypeAlias = 'SecureValue'
AnySecureValueError: TypeAlias = Union['SecureValueError', 'SecureValueErrorData', 'SecureValueErrorFile', 'SecureValueErrorFiles', 'SecureValueErrorFrontSide', 'SecureValueErrorReverseSide', 'SecureValueErrorSelfie', 'SecureValueErrorTranslationFile', 'SecureValueErrorTranslationFiles']
AnySecureValueHash: TypeAlias = 'SecureValueHash'
AnySecureValueType: TypeAlias = Union['SecureValueTypeAddress', 'SecureValueTypeBankStatement', 'SecureValueTypeDriverLicense', 'SecureValueTypeEmail', 'SecureValueTypeIdentityCard', 'SecureValueTypeInternalPassport', 'SecureValueTypePassport', 'SecureValueTypePassportRegistration', 'SecureValueTypePersonalDetails', 'SecureValueTypePhone', 'SecureValueTypeRentalAgreement', 'SecureValueTypeTemporaryRegistration', 'SecureValueTypeUtilityBill']
AnySendAsPeer: TypeAlias = 'SendAsPeer'
AnySendMessageAction: TypeAlias = Union['SendMessageCancelAction', 'SendMessageChooseContactAction', 'SendMessageChooseStickerAction', 'SendMessageEmojiInteraction', 'SendMessageEmojiInteractionSeen', 'SendMessageGamePlayAction', 'SendMessageGeoLocationAction', 'SendMessageHistoryImportAction', 'SendMessageRecordAudioAction', 'SendMessageRecordRoundAction', 'SendMessageRecordVideoAction', 'SendMessageTextDraftAction', 'SendMessageTypingAction', 'SendMessageUploadAudioAction', 'SendMessageUploadDocumentAction', 'SendMessageUploadPhotoAction', 'SendMessageUploadRoundAction', 'SendMessageUploadVideoAction', 'SpeakingInGroupCallAction']
AnyShippingOption: TypeAlias = 'ShippingOption'
AnySmsJob: TypeAlias = 'SmsJob'
AnySmsjobsEligibilityToJoin: TypeAlias = 'SmsjobsEligibleToJoin'
AnySmsjobsStatus: TypeAlias = 'SmsjobsStatus'
AnySponsoredMessage: TypeAlias = 'SponsoredMessage'
AnySponsoredMessageReportOption: TypeAlias = 'SponsoredMessageReportOption'
AnySponsoredPeer: TypeAlias = 'SponsoredPeer'
AnyStarGift: TypeAlias = Union['StarGift', 'StarGiftUnique']
AnyStarGiftActiveAuctionState: TypeAlias = 'StarGiftActiveAuctionState'
AnyStarGiftAttribute: TypeAlias = Union['StarGiftAttributeBackdrop', 'StarGiftAttributeModel', 'StarGiftAttributeOriginalDetails', 'StarGiftAttributePattern']
AnyStarGiftAttributeCounter: TypeAlias = 'StarGiftAttributeCounter'
AnyStarGiftAttributeId: TypeAlias = Union['StarGiftAttributeIdBackdrop', 'StarGiftAttributeIdModel', 'StarGiftAttributeIdPattern']
AnyStarGiftAttributeRarity: TypeAlias = Union['StarGiftAttributeRarity', 'StarGiftAttributeRarityEpic', 'StarGiftAttributeRarityLegendary', 'StarGiftAttributeRarityRare', 'StarGiftAttributeRarityUncommon']
AnyStarGiftAuctionAcquiredGift: TypeAlias = 'StarGiftAuctionAcquiredGift'
AnyStarGiftAuctionRound: TypeAlias = Union['StarGiftAuctionRound', 'StarGiftAuctionRoundExtendable']
AnyStarGiftAuctionState: TypeAlias = Union['StarGiftAuctionState', 'StarGiftAuctionStateFinished', 'StarGiftAuctionStateNotModified']
AnyStarGiftAuctionUserState: TypeAlias = 'StarGiftAuctionUserState'
AnyStarGiftBackground: TypeAlias = 'StarGiftBackground'
AnyStarGiftCollection: TypeAlias = 'StarGiftCollection'
AnyStarGiftUpgradePrice: TypeAlias = 'StarGiftUpgradePrice'
AnyStarRefProgram: TypeAlias = 'StarRefProgram'
AnyStarsAmount: TypeAlias = Union['StarsAmount', 'StarsTonAmount']
AnyStarsGiftOption: TypeAlias = 'StarsGiftOption'
AnyStarsGiveawayOption: TypeAlias = 'StarsGiveawayOption'
AnyStarsGiveawayWinnersOption: TypeAlias = 'StarsGiveawayWinnersOption'
AnyStarsRating: TypeAlias = 'StarsRating'
AnyStarsRevenueStatus: TypeAlias = 'StarsRevenueStatus'
AnyStarsSubscription: TypeAlias = 'StarsSubscription'
AnyStarsSubscriptionPricing: TypeAlias = 'StarsSubscriptionPricing'
AnyStarsTopupOption: TypeAlias = 'StarsTopupOption'
AnyStarsTransaction: TypeAlias = 'StarsTransaction'
AnyStarsTransactionPeer: TypeAlias = Union['StarsTransactionPeer', 'StarsTransactionPeerAPI', 'StarsTransactionPeerAds', 'StarsTransactionPeerAppStore', 'StarsTransactionPeerFragment', 'StarsTransactionPeerPlayMarket', 'StarsTransactionPeerPremiumBot', 'StarsTransactionPeerUnsupported']
AnyStatsAbsValueAndPrev: TypeAlias = 'StatsAbsValueAndPrev'
AnyStatsBroadcastStats: TypeAlias = 'StatsBroadcastStats'
AnyStatsDateRangeDays: TypeAlias = 'StatsDateRangeDays'
AnyStatsGraph: TypeAlias = Union['StatsGraph', 'StatsGraphAsync', 'StatsGraphError']
AnyStatsGroupTopAdmin: TypeAlias = 'StatsGroupTopAdmin'
AnyStatsGroupTopInviter: TypeAlias = 'StatsGroupTopInviter'
AnyStatsGroupTopPoster: TypeAlias = 'StatsGroupTopPoster'
AnyStatsMegagroupStats: TypeAlias = 'StatsMegagroupStats'
AnyStatsMessageStats: TypeAlias = 'StatsMessageStats'
AnyStatsPercentValue: TypeAlias = 'StatsPercentValue'
AnyStatsPublicForwards: TypeAlias = 'StatsPublicForwards'
AnyStatsStoryStats: TypeAlias = 'StatsStoryStats'
AnyStatsURL: TypeAlias = 'StatsURL'
AnyStickerKeyword: TypeAlias = 'StickerKeyword'
AnyStickerPack: TypeAlias = 'StickerPack'
AnyStickerSet: TypeAlias = 'StickerSet'
AnyStickerSetCovered: TypeAlias = Union['StickerSetCovered', 'StickerSetFullCovered', 'StickerSetMultiCovered', 'StickerSetNoCovered']
AnyStickersSuggestedShortName: TypeAlias = 'StickersSuggestedShortName'
AnyStorageFileType: TypeAlias = Union['StorageFileGif', 'StorageFileJpeg', 'StorageFileMov', 'StorageFileMp3', 'StorageFileMp4', 'StorageFilePartial', 'StorageFilePdf', 'StorageFilePng', 'StorageFileUnknown', 'StorageFileWebp']
AnyStoriesAlbums: TypeAlias = Union['StoriesAlbums', 'StoriesAlbumsNotModified']
AnyStoriesAllStories: TypeAlias = Union['StoriesAllStories', 'StoriesAllStoriesNotModified']
AnyStoriesCanSendStoryCount: TypeAlias = 'StoriesCanSendStoryCount'
AnyStoriesFoundStories: TypeAlias = 'StoriesFoundStories'
AnyStoriesPeerStories: TypeAlias = 'StoriesPeerStories'
AnyStoriesStealthMode: TypeAlias = 'StoriesStealthMode'
AnyStoriesStories: TypeAlias = 'StoriesStories'
AnyStoriesStoryReactionsList: TypeAlias = 'StoriesStoryReactionsList'
AnyStoriesStoryViews: TypeAlias = 'StoriesStoryViews'
AnyStoriesStoryViewsList: TypeAlias = 'StoriesStoryViewsList'
AnyStoryAlbum: TypeAlias = 'StoryAlbum'
AnyStoryFwdHeader: TypeAlias = 'StoryFwdHeader'
AnyStoryItem: TypeAlias = Union['StoryItem', 'StoryItemDeleted', 'StoryItemSkipped']
AnyStoryReaction: TypeAlias = Union['StoryReaction', 'StoryReactionPublicForward', 'StoryReactionPublicRepost']
AnyStoryView: TypeAlias = Union['StoryView', 'StoryViewPublicForward', 'StoryViewPublicRepost']
AnyStoryViews: TypeAlias = 'StoryViews'
AnySuggestedPost: TypeAlias = 'SuggestedPost'
AnyTextWithEntities: TypeAlias = 'TextWithEntities'
AnyTheme: TypeAlias = 'Theme'
AnyThemeSettings: TypeAlias = 'ThemeSettings'
AnyTimezone: TypeAlias = 'Timezone'
AnyTodoCompletion: TypeAlias = 'TodoCompletion'
AnyTodoItem: TypeAlias = 'TodoItem'
AnyTodoList: TypeAlias = 'TodoList'
AnyTopPeer: TypeAlias = 'TopPeer'
AnyTopPeerCategory: TypeAlias = Union['TopPeerCategoryBotsApp', 'TopPeerCategoryBotsInline', 'TopPeerCategoryBotsPM', 'TopPeerCategoryChannels', 'TopPeerCategoryCorrespondents', 'TopPeerCategoryForwardChats', 'TopPeerCategoryForwardUsers', 'TopPeerCategoryGroups', 'TopPeerCategoryPhoneCalls']
AnyTopPeerCategoryPeers: TypeAlias = 'TopPeerCategoryPeers'
AnyUpdate: TypeAlias = Union['UpdateAttachMenuBots', 'UpdateAutoSaveSettings', 'UpdateBotBusinessConnect', 'UpdateBotCallbackQuery', 'UpdateBotChatBoost', 'UpdateBotChatInviteRequester', 'UpdateBotCommands', 'UpdateBotDeleteBusinessMessage', 'UpdateBotEditBusinessMessage', 'UpdateBotInlineQuery', 'UpdateBotInlineSend', 'UpdateBotMenuButton', 'UpdateBotMessageReaction', 'UpdateBotMessageReactions', 'UpdateBotNewBusinessMessage', 'UpdateBotPrecheckoutQuery', 'UpdateBotPurchasedPaidMedia', 'UpdateBotShippingQuery', 'UpdateBotStopped', 'UpdateBotWebhookJSON', 'UpdateBotWebhookJSONQuery', 'UpdateBusinessBotCallbackQuery', 'UpdateChannel', 'UpdateChannelAvailableMessages', 'UpdateChannelMessageForwards', 'UpdateChannelMessageViews', 'UpdateChannelParticipant', 'UpdateChannelReadMessagesContents', 'UpdateChannelTooLong', 'UpdateChannelUserTyping', 'UpdateChannelViewForumAsMessages', 'UpdateChannelWebPage', 'UpdateChat', 'UpdateChatDefaultBannedRights', 'UpdateChatParticipant', 'UpdateChatParticipantAdd', 'UpdateChatParticipantAdmin', 'UpdateChatParticipantDelete', 'UpdateChatParticipantRank', 'UpdateChatParticipants', 'UpdateChatUserTyping', 'UpdateConfig', 'UpdateContactsReset', 'UpdateDcOptions', 'UpdateDeleteChannelMessages', 'UpdateDeleteGroupCallMessages', 'UpdateDeleteMessages', 'UpdateDeleteQuickReply', 'UpdateDeleteQuickReplyMessages', 'UpdateDeleteScheduledMessages', 'UpdateDialogFilter', 'UpdateDialogFilterOrder', 'UpdateDialogFilters', 'UpdateDialogPinned', 'UpdateDialogUnreadMark', 'UpdateDraftMessage', 'UpdateEditChannelMessage', 'UpdateEditMessage', 'UpdateEmojiGameInfo', 'UpdateEncryptedChatTyping', 'UpdateEncryptedMessagesRead', 'UpdateEncryption', 'UpdateFavedStickers', 'UpdateFolderPeers', 'UpdateGeoLiveViewed', 'UpdateGroupCall', 'UpdateGroupCallChainBlocks', 'UpdateGroupCallConnection', 'UpdateGroupCallEncryptedMessage', 'UpdateGroupCallMessage', 'UpdateGroupCallParticipants', 'UpdateInlineBotCallbackQuery', 'UpdateLangPack', 'UpdateLangPackTooLong', 'UpdateLoginToken', 'UpdateMessageExtendedMedia', 'UpdateMessageID', 'UpdateMessagePoll', 'UpdateMessagePollVote', 'UpdateMessageReactions', 'UpdateMonoForumNoPaidException', 'UpdateMoveStickerSetToTop', 'UpdateNewAuthorization', 'UpdateNewChannelMessage', 'UpdateNewEncryptedMessage', 'UpdateNewMessage', 'UpdateNewQuickReply', 'UpdateNewScheduledMessage', 'UpdateNewStickerSet', 'UpdateNewStoryReaction', 'UpdateNotifySettings', 'UpdatePaidReactionPrivacy', 'UpdatePeerBlocked', 'UpdatePeerHistoryTTL', 'UpdatePeerLocated', 'UpdatePeerSettings', 'UpdatePeerWallpaper', 'UpdatePendingJoinRequests', 'UpdatePhoneCall', 'UpdatePhoneCallSignalingData', 'UpdatePinnedChannelMessages', 'UpdatePinnedDialogs', 'UpdatePinnedForumTopic', 'UpdatePinnedForumTopics', 'UpdatePinnedMessages', 'UpdatePinnedSavedDialogs', 'UpdatePrivacy', 'UpdatePtsChanged', 'UpdateQuickReplies', 'UpdateQuickReplyMessage', 'UpdateReadChannelDiscussionInbox', 'UpdateReadChannelDiscussionOutbox', 'UpdateReadChannelInbox', 'UpdateReadChannelOutbox', 'UpdateReadFeaturedEmojiStickers', 'UpdateReadFeaturedStickers', 'UpdateReadHistoryInbox', 'UpdateReadHistoryOutbox', 'UpdateReadMessagesContents', 'UpdateReadMonoForumInbox', 'UpdateReadMonoForumOutbox', 'UpdateReadStories', 'UpdateRecentEmojiStatuses', 'UpdateRecentReactions', 'UpdateRecentStickers', 'UpdateSavedDialogPinned', 'UpdateSavedGifs', 'UpdateSavedReactionTags', 'UpdateSavedRingtones', 'UpdateSentPhoneCode', 'UpdateSentStoryReaction', 'UpdateServiceNotification', 'UpdateSmsJob', 'UpdateStarGiftAuctionState', 'UpdateStarGiftAuctionUserState', 'UpdateStarGiftCraftFail', 'UpdateStarsBalance', 'UpdateStarsRevenueStatus', 'UpdateStickerSets', 'UpdateStickerSetsOrder', 'UpdateStoriesStealthMode', 'UpdateStory', 'UpdateStoryID', 'UpdateTheme', 'UpdateTranscribedAudio', 'UpdateUser', 'UpdateUserEmojiStatus', 'UpdateUserName', 'UpdateUserPhone', 'UpdateUserStatus', 'UpdateUserTyping', 'UpdateWebPage', 'UpdateWebViewResultSent']
AnyUpdates: TypeAlias = Union['UpdateShort', 'UpdateShortChatMessage', 'UpdateShortMessage', 'UpdateShortSentMessage', 'Updates', 'UpdatesCombined', 'UpdatesTooLong']
AnyUpdatesChannelDifference: TypeAlias = Union['UpdatesChannelDifference', 'UpdatesChannelDifferenceEmpty', 'UpdatesChannelDifferenceTooLong']
AnyUpdatesDifference: TypeAlias = Union['UpdatesDifference', 'UpdatesDifferenceEmpty', 'UpdatesDifferenceSlice', 'UpdatesDifferenceTooLong']
AnyUpdatesState: TypeAlias = 'UpdatesState'
AnyUploadCdnFile: TypeAlias = Union['UploadCdnFile', 'UploadCdnFileReuploadNeeded']
AnyUploadFile: TypeAlias = Union['UploadFile', 'UploadFileCdnRedirect']
AnyUploadWebFile: TypeAlias = 'UploadWebFile'
AnyUrlAuthResult: TypeAlias = Union['UrlAuthResultAccepted', 'UrlAuthResultDefault', 'UrlAuthResultRequest']
AnyUser: TypeAlias = Union['User', 'UserEmpty']
AnyUserFull: TypeAlias = 'UserFull'
AnyUserProfilePhoto: TypeAlias = Union['UserProfilePhoto', 'UserProfilePhotoEmpty']
AnyUserStatus: TypeAlias = Union['UserStatusEmpty', 'UserStatusLastMonth', 'UserStatusLastWeek', 'UserStatusOffline', 'UserStatusOnline', 'UserStatusRecently']
AnyUsername: TypeAlias = 'Username'
AnyUsersSavedMusic: TypeAlias = Union['UsersSavedMusic', 'UsersSavedMusicNotModified']
AnyUsersUserFull: TypeAlias = 'UsersUserFull'
AnyUsersUsers: TypeAlias = Union['UsersUsers', 'UsersUsersSlice']
AnyVideoSize: TypeAlias = Union['VideoSize', 'VideoSizeEmojiMarkup', 'VideoSizeStickerMarkup']
AnyWallPaper: TypeAlias = Union['WallPaper', 'WallPaperNoFile']
AnyWallPaperSettings: TypeAlias = 'WallPaperSettings'
AnyWebAuthorization: TypeAlias = 'WebAuthorization'
AnyWebDocument: TypeAlias = Union['WebDocument', 'WebDocumentNoProxy']
AnyWebPage: TypeAlias = Union['WebPage', 'WebPageEmpty', 'WebPageNotModified', 'WebPagePending']
AnyWebPageAttribute: TypeAlias = Union['WebPageAttributeStarGiftAuction', 'WebPageAttributeStarGiftCollection', 'WebPageAttributeStickerSet', 'WebPageAttributeStory', 'WebPageAttributeTheme', 'WebPageAttributeUniqueStarGift']
AnyWebViewMessageSent: TypeAlias = 'WebViewMessageSent'
AnyWebViewResult: TypeAlias = 'WebViewResultUrl'
